### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Haaxor1689** [TerezaKlikova/PriruckaSenzorickeIntegrace#1]
## Header
- [x] Logo
- [x] Nazov - PriruckaSenzorickeIntegrace
- [x] Stiahnut PDF
- [x] Uzitocne odkazy
- [x] Pouzite zdroje

## Homepage:
- [x] Uvodne slova, dovod vytvorenia, pre koho (podporny material)
- [ ] Zakoncit uvod tlacitkom na stiahnutie PDF
- [x] Prehlad kapitol (karticky) - nadpis

## Kapitoly
- [x] Ikonka
- [x] Kazda kapitola svoju farbu
- [x] Zoznam kapitol na boku
- [x] Na mobile na spodku tabs s ikonkami
- [x] Vybrana kapitola ma rozbalene podkapitoly
- [x] Podkapitoly "Co je xyz" a "Aktivity na xyz"
- [ ] Tagy zmyslov k aktivitam

Zoznam kapitol:
- Senzorická integrace (dite) - https://game-icons.net/1x1/lorc/brain.html
- Vestibulární vnímání (balanc) - https://game-icons.net/1x1/delapouite/jumping-rope.html
- Proprioceptivní vnímání (yoga) - https://game-icons.net/1x1/lorc/sensuousness.html
- Hmatové vnímání (ruka) -  https://game-icons.net/1x1/sbed/hand.html
- Zrakové vnímání (oko) - https://game-icons.net/1x1/lorc/semi-closed-eye.html
- Sluchové vnímání (ucho) - https://game-icons.net/1x1/delapouite/human-ear.html
- Čichové vnímání (nos) - https://game-icons.net/1x1/delapouite/nose-front.html
- Chuťové vnímání (nos) - https://game-icons.net/1x1/delapouite/tongue.html

## Odkazy
- [x] Terapeuti, strediska, atd.
- [ ] Adresa, mail, web

## Pouzite zdroje
- [x] Bibliografie
